### ISSUE TITLE
"heroku run rake" doesn't work

### ISSUE THREAD

**Issue by omoindrot** [Workshop-Polytechnique/Cours_3#1]
J'avais un petit problème (depuis l'X) pour lancer la dernière commande d'update de la base de données:
"heroku run rake db:create db:migrate db:seed"

Apparemment, le proxy de l'X bloque le porte utilisé (5000), donc il faut plutôt utiliser:
"heroku run:detached rake db:create db:migrate db:seed"

**Comment by ghislaindj** [comment]
Etonnant ça, est ce que le heroku logs marche ensuite ou bien il est bloqué ?

**Comment by omoindrot** [comment]
Non heroku logs marche bien
