### ISSUE TITLE
Étape 1: création du modèle Booking

### ISSUE THREAD

**Issue by omoindrot** [Workshop-Polytechnique/Cours_3#3]
On écrit avec le champ "number":
$ rails g model Booking user_name:string number:integer show:references

Mais il faudrait plutôt créer avec le champ "seats"
$ rails g model Booking user_name:string seats:integer show:references

**Comment by ghislaindj** [comment]
Tu as complètement raison, merci :+1: 

La prochaine fois tu nous fais une pull request :yum:  ?

**Comment by omoindrot** [comment]
Haha ok
